version: '3.9'

services:
    django:
        build:
            context: .
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py collectstatic --noinput &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        volumes:
            #This line allows us to edit files in development
            #without having to restart the server.
            - ./Django:/Django
            - ./data/web:/vol/web
        environment:
            - SECRET_KEY=developmentsecretkey
            - DEBUG=1
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASS=pass
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=pass
